# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Karim Romani
title: Customer Success Specialist - Transitioning to Cyber Security
email: karim.romani(at)outlook(dot)com
website: www.karimromani.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Defirion
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: karim__rom
linkedin_username: karim-romani
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Teleperformance (NDA client)
        sub_title: Customer Service Specialist – SaaS Productivity Platform Support
        caption: Feb 2025 - Present · Greece · Remote
        description: | # this will include new lines to allow paragraphs
          Resolved SaaS account access and workspace issues (provisioning, permissions, MFA), and guided users on best practices.

          Triaged tickets with clear diagnostics and context for seamless handoffs; followed runbooks and SOPs for consistent outcomes.

          Collaborated with internal teams to surface product feedback and improve help content for recurring issues.

      - layout: left
        title: Teleperformance
        sub_title: Content Moderator – Proactive Operations (NDA client)
        caption: Apr 2022 - Dec 2024 · Athens, Attiki, Greece · Remote
        description: | # this will include new lines to allow paragraphs
          Reviewed user‑generated content against community guidelines and IP policies; safeguarded community integrity.

          Handled sensitive material with professionalism and attention to detail; maintained high accuracy and throughput.

          Partnered with cross‑functional teams to refine moderation workflows and meet KPI commitments.

      - layout: left
        title: Teleperformance
        sub_title: Customer Service Specialist – Banking Support (Contract, NDA client)
        caption: Oct 2021 - Jan 2022 · Greece
        description: | # this will include new lines to allow paragraphs
          Supported retail banking users via secure channels; resolved access and account‑servicing inquiries within SLA and compliance guidelines.

          Performed user verification/KYC steps per procedure; documented exceptions and escalated edge cases with full context.

          Maintained accurate ticketing/CRM records to ensure reliable handoffs across shifts and teams.

      - layout: left
        title: Teleperformance
        sub_title: Customer Service Specialist – Gaming Platform Support (NDA client)
        caption: Sep 2018 - Sep 2021 · Athens, Attiki, Greece
        description: | # this will include new lines to allow paragraphs
          Supported end users via email, consistently exceeding satisfaction and resolution‑time targets.

          Documented procedures, standardized ticket notes, and ensured accurate escalations to L2/L3.

          Tools: Help desk and CRM platforms (e.g., Zendesk, Salesforce), internal knowledge bases.

      - layout: left
        title: Dactyl SA
        sub_title: Jewelry Maker
        caption: Mar 2012 - Sep 2016
        description: | # this will include new lines to allow paragraphs
          Crafted high-quality, custom jewelry pieces, specializing in high-end college and university class rings as well as varsity rings, ensuring precision and adherence to strict design specifications.

          Demonstrated strong problem-solving skills by troubleshooting and resolving production challenges efficiently.

          Consistently met all production deadlines, even under tight schedules, while maintaining exceptional attention to detail and quality standards.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ACG - Deree College
        caption: Relevant coursework
        sub_title: BSc in Business Administration 2007 - 2009
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          At Deree’s School of Business & Economics, business administration studies emphasized applied learning—projects, presentations, and cross‑functional teamwork—helping build confidence under tight deadlines while keeping outcomes aligned with real business practice. The campus community and student organizations created the space to balance academics with extracurricular commitments and grow soft skills alongside technical knowledge. 
          
          Though studies concluded after two years, the experience delivered durable skills and perspective that carried forward into later roles and projects

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
